### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by KCMarch** [mattmas/Metamorphosis#26]
**Posting on behalf of Peter Bruckner:**

Metamorphosis looks like a great tool for comparing Revit models in a granular way.  Problem I'm having (on two separate computer systems (using Revit 2017) ends up with the same dialog error message:

Error! System. Data.SQLite.SQLiteException (Ox80004005): SQL
logic erroror missing database
near syntax error
at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String
strSqI, SQLiteStatement previous, Ulnt32 timeoutMS, String& strRemain)
at System Data. SQLite. SQLiteCommand. auiIdNextCommand0
at System. Data. SQLite. SQLiteDataReader. NextResuIt0
at System. Data. SQLite. SQLiteDataReader.. ctor(SQLiteCommand cmd,
Commandaehavior behave)
System. Data. SQLite.SQLiteCommand. ExecuteReader(Command8ehavior
behavior)
System. Data. SQLite.SQLiteCommand. ExecuteNonQueMCommand8ehavi
or behavior)
at Metam orphosis. SnapshotMaker. updateHeaderTabIe0
at Metamorphosis. SnapshotMaker. exportParameterData0
at Metamorphosis. SnapshotMaker.Export0
at Metamorphosis. Snapshot. Execute(ExternaICommandData
commandData, String& message, ElementSet elements) 

Am I missing a component or related program (like SQL?)

Any help you can offer would be very welcome!

**Comment by thazell** [comment]
Hi Peter.  Are you running this on a detached model?

**Comment by mattmas** [comment]
That’s a good thought – it feels like there’s some kind of unusual character in the filename, or something else odd (detached models have no path).

-Matt

**Comment by pj-pilot** [comment]
This is a shared (central) file.  Should I detach it first?

**Comment by mattmas** [comment]
No – if it’s a central file, then it’s not the issue Timon is suggesting.
Don’t detach it.

Is there any chance you could share the model with me?

Thanks,
Matt

Matt Mason
IMAGINiT Technologies
Brookline, MA
T: +1 508-663-1462
Email: mmason@rand.com<mailto:mmason@rand.com>
imaginit.com<http://www.imaginit.com/>

**Comment by pj-pilot** [comment]
I'll be glad to share the model, although it must be kept confidential.
Here's al link to the architectural file:� � https://www.dropbox.com/sh/ylgv9i95b0666zp/AAA11D0SB4XDPM9KgJIxPtx2a?dl=0
Regards,
Peter
I'll put it up on DropBox for you

---------------------------- Original Message ----------------------------

Subject: Re: [mattmas/Metamorphosis] SQL Error (#26)

**Comment by mattmas** [comment]
I have retrieved it – please remove from Dropbox

**Comment by mattmas** [comment]
Peter (et al), 
I've posted a new version of Metamorphosis - 1.2.
It includes:
- Support for Revit 2019-2015
- A workaround for Peter's issue (Peter - keep an eye on a group called "DS Outlet" in your model, I am suspicious it is somehow corrupt).

**Comment by pj-pilot** [comment]
I downloaded the latest link (note the date on the msi is 1-31-2017.
Still get the same error message.
Still have a strong project need for metamorphosis' functionality.

**Comment by mattmas** [comment]
Peter,
If you download from here, the date on the MSI file should be 5/5/2018?
https://github.com/mattmas/Metamorphosis/blob/master/addin/MetamorphosisInstaller.zip

-Matt

**Comment by pj-pilot** [comment]
Matt:
Here is a screenshot from my visit to the link just minutes ago.
(The Zip file is dated today, but the .msi is dated 1/31/2017.)
Is it necessary to remove the plugin from Revit  first?  
Regards,
Peter


---------------------------- Original Message ----------------------------

Subject: Re: [mattmas/Metamorphosis] SQL Error (#26)

**Comment by mattmas** [comment]
Peter - I don't see the screenshot, but give the installer a try.

You may need to uninstall/reinstall.
After installing, on the Snapshot command the window should show "Metamorphosis 1.2.0.0" in the dialog titlebar.

**Comment by pj-pilot** [comment]
Thanks.  I did a full uninstall.  (Renaming the old files in the addins directory did not work, had to remove them entirely).  Now the dialog box reads as 1.2.0.0.
Regards,
Peter

**Comment by mattmas** [comment]
And is the issue resolved?

**Comment by pj-pilot** [comment]
Matt:
Sadly not.� I just tried to snapshot another file and got the same dialog message:

Might there be a missing SQL database program that is
needed?
Regards,
Peter
�
---------------------------- Original Message ----------------------------
Subject: Re: [mattmas/Metamorphosis] SQL Error (#26)

**Comment by mattmas** [comment]
Drat. When I looked at it, I wasn't getting exactly the same issue as you, but I hoped it was resolved when it worked for me. Re-opening the issue.

**Comment by hamdibr** [comment]
Hello everyone,
I still have the same error, i use Revit 2019. I try it even in a file with just 4 wall and nothing elese.
Is it a problem of caractere, since i use french version of revit ?

![image](https://user-images.githubusercontent.com/26900980/77512936-44567580-6e74-11ea-9937-a0d5e005d540.png)

**Comment by mattmas** [comment]
Yes, it is a problem that we’re not properly handling certain words that contain ‘ within them.
I’m preparing an update for Revit 2021 in the next week or two, I’ll see if we can get that issue addressed as well.

-Matt

**Comment by hamdibr** [comment]
@mattmas  thx
